import "./globals.css"
import { TanstackProvider } from "./providers/ReactQueryProvider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <main className="h-screen">
          <TanstackProvider>
            {children}
          </TanstackProvider>
        </main>
      </body>
    </html >
  );
}
